# Generated by Django 5.1.6 on 2025-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_department', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=30)),
                ('manager_designation', models.CharField(max_length=100)),
                ('manager_department', models.CharField(max_length=100)),
                ('manager_salary', models.IntegerField()),
            ],
        ),
    ]
