# Generated by Django 5.1.6 on 2025-02-28 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_academic_discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must start with 0 and be 11 digits long', regex='^0\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email has already been registered.'}, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_academic_discipline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must start with 0 and be 11 digits long', regex='^0\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email has already been registered.'}, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
