# Generated by Django 5.1.6 on 2025-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_manager_manager_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
