# Generated by Django 5.1.6 on 2025-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employee_emp_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='work_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
