# Generated by Django 5.1.6 on 2025-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_employee_status_remove_manager_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
