# Generated by Django 5.1.6 on 2025-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employee_date_of_birth_manager_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
