# Generated by Django 5.1.6 on 2025-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_employee_salary_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
