# Generated by Django 5.1.6 on 2025-03-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_employee_emp_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_tax',
        ),
    ]
